# Generated by Django 4.2.7 on 2023-11-23 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numArduino', models.CharField(max_length=100)),
                ('isOkno', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numArduino', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200, null=True)),
                ('windowsAreOpened', models.BooleanField(default=False)),
                ('idDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='core.arduinodevices')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
