# Generated by Django 4.2.7 on 2023-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_arduinodevices_isokno'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='windowsAreBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
