# Generated by Django 4.2.7 on 2023-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_devices_windowsareblocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinodevices',
            name='isWindow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devices',
            name='gaz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='vlazhnost',
            field=models.FloatField(null=True),
        ),
    ]
