# Generated by Django 4.2.7 on 2023-11-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_arduinodevices_iswindow_devices_gaz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='gaz',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devices',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devices',
            name='vlazhnost',
            field=models.FloatField(default=0),
        ),
    ]
