# Generated by Django 4.2.7 on 2023-11-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numArduino', models.CharField(max_length=100)),
                ('isOkno', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numArduino', models.CharField(max_length=100)),
                ('windowName', models.CharField(max_length=200, null=True)),
                ('idDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='arduino.arduinodevices')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numArduino', models.CharField(max_length=100)),
                ('roomName', models.CharField(max_length=200)),
                ('idDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='arduino.arduinodevices')),
            ],
        ),
    ]
