# Generated by Django 4.2.7 on 2023-11-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
        ('datchiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('temperature', models.FloatField()),
                ('vlazhnost', models.FloatField()),
                ('gaz', models.FloatField()),
                ('idWindow', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='okoshko', to='arduino.windows')),
            ],
        ),
        migrations.DeleteModel(
            name='Okno',
        ),
    ]
