# Generated by Django 4.2.7 on 2023-11-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
        ('datchiki', '0002_windowinfo_delete_okno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowinfo',
            name='gaz',
        ),
        migrations.RemoveField(
            model_name='windowinfo',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='windowinfo',
            name='vlazhnost',
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('vlazhnost', models.FloatField()),
                ('gaz', models.FloatField()),
                ('idRoom', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komnatka', to='arduino.rooms')),
            ],
        ),
    ]
